### ISSUE TITLE
Selfhost stashface

### ISSUE THREAD

**Issue by Joly0** [cc1234475/visage-ml#1]
Hey, as https://huggingface.co/spaces/cc1234/stashface/tree/main was down previously, i wanted to know if its possible to self-host it? Either by building it myself or using pre-built docker containers.
I have knowledge with building and working with docker containers and therefore would probably have no problem getting them to work, but i have looked through this repo and the dockerfiles provided here look outdated

Would be cool if it were possible :)

**Comment by Joly0** [comment]
@cc1234475 ?

**Comment by cc1234475** [comment]
The docker image in these repos where created before I started hosting a version on hugging face.
your best bet it take the repo from hugging face and taking that locally and running it with virtualenv.

Then modify the visage plugin in stash to point to your new endpoint in both the js and yaml files.

Hit me up on discord and I can try and help where I can.
